version: '3'
services:
  yumemi_view:
    build: ./view
    container_name: 'view'
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    env_file:
      - ./view/.env.local