on:
  pull_request:
    branches:
      - develop
    paths:
      - "view/**"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ./view/src/package-lock.json
      - name: npm install
        working-directory: ./view/src
        run: npm install
      - name: format
        working-directory: ./view/src
        run: npm run format
      # - name: Lint
      # working-directory: ./frontend/src
      # run: npm run lint
      - uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: formatted by workflow
